/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import static ventanas.login.id_usuario;

/**
 *
 * @author mb
 */
public class CargarExperiencia extends javax.swing.JFrame {

    /**
     * Creates new form CargarExperiencia
     */
    public CargarExperiencia() throws ParseException {
        initComponents();
        setSize(495, 289);
        setResizable(false);
        setTitle("Cargar experiencia");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        txt_empresa = new javax.swing.JTextField();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        txt_puesto = new javax.swing.JTextField();
        jLabel_Nombre4 = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jButton_guardar = new javax.swing.JButton();
        txt_hasta = new com.toedter.calendar.JDateChooser();
        txt_desde = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_empresa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_empresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setText("Experiencia");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setText("Empresa:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_puesto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_puesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puestoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 210, -1));

        jLabel_Nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre4.setText("Puesto:");
        getContentPane().add(jLabel_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Email.setText("Desde:");
        getContentPane().add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel_Nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre2.setText("Hasta:");
        getContentPane().add(jLabel_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jButton_guardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.setBorder(null);
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 210, 35));

        txt_hasta.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 140, -1));

        txt_desde.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        int validacion = 0, nums = 0;
        int fechas = 0;
        String empresa, puesto, desde, hasta;

        empresa = txt_empresa.getText().trim();
        puesto = txt_puesto.getText().trim();
        desde = ((JTextField) txt_desde.getDateEditor().getUiComponent()).getText();
        hasta = ((JTextField) txt_hasta.getDateEditor().getUiComponent()).getText();

        if (txt_desde.getDate() == null) {
            txt_desde.setBackground(Color.red);
            validacion++;
        } else {
            txt_desde.setBackground(Color.white);
        }

        if (txt_hasta.getDate() == null) {
            txt_hasta.setBackground(Color.red);
            validacion++;
        } else {
            txt_hasta.setBackground(Color.white);
        }

        if (empresa.equals("")) {
            txt_empresa.setBackground(Color.red);
            validacion++;
        } else {
            txt_empresa.setBackground(Color.white);
        }
        if(empresa.matches("[0-9]*")){
            nums++;
        }

        if (puesto.equals("")) {
            txt_puesto.setBackground(Color.red);
            validacion++;
        } else {
            txt_puesto.setBackground(Color.white);
        }
        if(puesto.matches("[0-9]*")){
            nums++;
        }

        String desde1 = new SimpleDateFormat("yyyy/MM/dd").format(this.txt_desde.getDate());
        String hasta1 = new SimpleDateFormat("yyyy/MM/dd").format(this.txt_hasta.getDate());

        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");

        try {
            System.out.println("Entro");
            Date f1 = formato.parse(desde1);
            Date f2 = formato.parse(hasta1);

            if (f1.after(f2)) {
                txt_desde.setBackground(Color.red);
                fechas++;
            } else {
                txt_hasta.setBackground(Color.white);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        System.out.println(login.id_usuario);
        if (validacion == 0 && fechas == 0 && nums == 0) {
            try {
                Connection cn2 = Conexion.conectar();

                PreparedStatement pst2 = cn2.prepareStatement(
                        "INSERT INTO experiencias (empresa, puesto, desde, hasta, id_usuario) VALUES (?,?,?,?,?)");
                pst2.setString(1, empresa);
                pst2.setString(2, puesto);
                pst2.setString(3, desde);
                pst2.setString(4, hasta);
                pst2.setString(5, login.id_usuario);

                pst2.executeUpdate();
                cn2.close();

                JOptionPane.showMessageDialog(null, "Guardado correcto!");

                txt_empresa.setText("");
                txt_puesto.setText("");
                txt_desde.setCalendar(null);
                txt_hasta.setCalendar(null);

            } catch (SQLException e) {
                System.err.println("Error al actualizar " + e);
            }
            System.out.println(nums);
        } else if (validacion > 0) {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        } else if (nums > 0) {
            JOptionPane.showMessageDialog(null, "Empresa y puesto solo pueden contener letras");
        } else {
            JOptionPane.showMessageDialog(null, "Desde no puede ser posterior a Hasta");
        }

    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void txt_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CargarExperiencia().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(CargarExperiencia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Nombre4;
    private javax.swing.JLabel jLabel_Titulo;
    private com.toedter.calendar.JDateChooser txt_desde;
    private javax.swing.JTextField txt_empresa;
    private com.toedter.calendar.JDateChooser txt_hasta;
    private javax.swing.JTextField txt_puesto;
    // End of variables declaration//GEN-END:variables
}
