/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;

/**
 *
 * @author mb
 */
public class MenuExperiencia extends javax.swing.JFrame {

    /**
     * Creates new form MenuExperiencia
     */
    public MenuExperiencia() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_gestionarExp = new javax.swing.JButton();
        jButton_cargarExp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_gestionarExp.setText("Gestionar experiencias");
        jButton_gestionarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gestionarExpActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_gestionarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 210, -1));

        jButton_cargarExp.setText("Cargar experiencia");
        jButton_cargarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cargarExpActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cargarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 210, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cargarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cargarExpActionPerformed
        CargarExperiencia cargar_exp;
        try {
            cargar_exp = new CargarExperiencia();
            cargar_exp.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(MenuExperiencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_cargarExpActionPerformed

    private void jButton_gestionarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gestionarExpActionPerformed
        GestionarExperiencias gestionar = new GestionarExperiencias();
        gestionar.setVisible(true);
    }//GEN-LAST:event_jButton_gestionarExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuExperiencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cargarExp;
    private javax.swing.JButton jButton_gestionarExp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
