/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.WindowConstants;

/**
 *
 * @author mb
 */
public class Usuario extends javax.swing.JFrame {
 String user;
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        user = login.user;      
        
        setSize(637, 289);
        setResizable(false);
        setTitle("Sesion de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton_Password = new javax.swing.JButton();
        jButton_CargarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Experiencias = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Informacion del usuario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opciones.png"))); // NOI18N
        jButton_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 120, 100));

        jButton_CargarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        jButton_CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CargarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, 100));

        jLabel1.setText("Cargar datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel2.setText("Cambiar contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 200, 120, -1));

        jButton_Experiencias.setIcon(new javax.swing.ImageIcon("C:\\Users\\mb\\Documents\\NetBeansProjects\\bolsaEmpleo\\src\\images\\creatividad.png")); // NOI18N
        jButton_Experiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExperienciasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Experiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 120, 100));

        jLabel4.setText("Experiencias");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CargarDatosActionPerformed
        InformacionUsuario informacion_usuario = new InformacionUsuario();
        informacion_usuario.setVisible(true);
    }//GEN-LAST:event_jButton_CargarDatosActionPerformed

    private void jButton_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PasswordActionPerformed
        RestaurarPassword restaurarPassword = new RestaurarPassword();
        restaurarPassword.setVisible(true);
    }//GEN-LAST:event_jButton_PasswordActionPerformed

    private void jButton_ExperienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExperienciasActionPerformed
        MenuExperiencia menu = new MenuExperiencia();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton_ExperienciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CargarDatos;
    private javax.swing.JButton jButton_Experiencias;
    private javax.swing.JButton jButton_Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
